CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(30) NOT NULL UNIQUE
);

CREATE TABLE wallets (
    wallet_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    balance DECIMAL(18, 2) NOT NULL DEFAULT 0.00,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE -- Delete row if user is deleted
);

-- ====================
-- MOCK DATA
-- ====================

INSERT INTO users (username) VALUES
    ('Alice'),
    ('Bob'),
    ('Charlie');

INSERT INTO wallets (user_id, balance) VALUES
    (1, 1000.00),
    (2, 250.50),
    (3, 0.00);